[package]
name = "editdistpy"
version = "0.4.0"
edition = "2024"
description = "Fast Levenshtein and Damerau optimal string alignment algorithms."
authors = ["mmb L"]
repository = "https://github.com/mammothb/editdistpy"
license = "MIT"

[lib]
name = "editdistpy"
crate-type = ["cdylib"]

[dependencies]
ahash = { version = "0.8.12" }
pyo3 = { version = "0.28.3", features = ["generate-import-lib"] }

[dev-dependencies]
itertools = { version = "0.15" }
rand = { version = "0.10.2" }
rstest = { version = "0.26.1" }

[features]
python = []
