[build-system]
requires = ["maturin>=1.13,<2"]
build-backend = "maturin"

[project]
name = "editdistpy"
version = "0.4.0"
requires-python = ">=3.10"
authors = [
    {name = "mmb L"},
]
description = "Fast Levenshtein and Damerau optimal string alignment algorithms."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["edit distance", "levenshtein", "damerau"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Rust",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
]

[project.urls]
Repository = "https://github.com/mammothb/editdistpy"
Changelog = "https://github.com/mammothb/editdistpy/blob/master/CHANGELOG.md"

[dependency-groups]
dev = [
    "basedpyright==1.39.3",
    "editdistance==0.8.1",
    "maturin==1.13.3",
    "pytest==9.1.1",
    "ruff==0.15.12",
]

[tool.basedpyright]
reportUnusedCallResult = "none"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W"]

[tool.ruff.lint.isort]
known-first-party = ["editdistpy"]

[tool.ruff.format]
quote-style = "double"

[tool.maturin]
features = ["pyo3/extension-module", "python"]
python-source = "python"
module-name = "editdistpy._editdistpy"

[tool.uv]
cache-keys = [
    { file = "**/*.rs" },
    { file = "Cargo.lock" },
    { file = "Cargo.toml" },
    { file = "pyproject.toml" },
    { file = "python/**/*" },
    { file = "rust-toolchain.toml" },
]
