name: Build editdistpy
description: Installs editdistpy
runs:
  using: composite
  steps:
    - name: Environment detail
      run: |
        uv pip list
      shell: bash -el {0}
    - name: Uninstall existing editdistpy
      run: |
        if uv pip show editdistpy 1>/dev/null; then
          uv pip uninstall -y editdistpy
        fi
      shell: bash -el {0}
    - name: Build editdistpy
      run: |
        uv pip install -v .
      shell: bash -el {0}
