name: Tests
on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  UV_LOCKED: 1
jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - &rust-cache
        name: Cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
      - name: Setup - uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
      - name: Check - Lint
        run: make lint
      - name: Check - Format
        run: make fmt
  test:
    name: Test (py${{ matrix.python-version }})
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *rust-cache
      - name: Setup - uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Test - Rust
        run: make test-rust
      - name: "Test - Rust (python feature)"
        run: make test-rust-python
      - name: Test - Python
        run: make test-python
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *rust-cache
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@7f4eb899022d8fe70b20c4f3de697aa85c309026 # v2.85.11
        with:
          tool: cargo-llvm-cov
      - name: Coverage
        run: make coverage-ci
      - name: Upload to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: false
