name: Wheel builder
on:
  push:
    tags:
      - "*"
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Build sdist
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b #v1.51.0
        with:
          command: sdist
          args: --out dist
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sdist
          path: dist
  linux:
    name: Build wheels (linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64
          - aarch64
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - *checkout
      - name: Build wheel
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b #v1.51.0
        with:
          target: ${{ matrix.target }}
          args: --release --out dist -i ${{ matrix.python }}
          manylinux: auto
          sccache: ${{ github.event_name != 'pull_request' }}
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wheel-linux-${{ matrix.target }}-${{ matrix.python }}
          path: dist
  musllinux:
    name: Build wheels (musllinux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - *checkout
      - name: Build wheel
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b #v1.51.0
        with:
          target: ${{ matrix.target }}
          args: --release --out dist -i ${{ matrix.python }}
          manylinux: musllinux_1_1
          sccache: ${{ github.event_name != 'pull_request' }}
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wheel-musl-${{ matrix.target }}-${{ matrix.python }}
          path: dist
  windows:
    name: Build wheels (windows)
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - x64
          - x86
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - *checkout
      - name: Build wheel
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b #v1.51.0
        with:
          target: ${{ matrix.target }}
          args: --release --out dist -i ${{ matrix.python }}
          sccache: ${{ github.event_name != 'pull_request' }}
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wheel-windows-${{ matrix.target }}-${{ matrix.python }}
          path: dist
  macos:
    name: Build wheels (macos)
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64
          - aarch64
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - *checkout
      - name: Build wheel
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b #v1.51.0
        with:
          target: ${{ matrix.target }}
          args: --release --out dist -i ${{ matrix.python }}
          sccache: ${{ github.event_name != 'pull_request' }}
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wheel-macos-${{ matrix.target }}-${{ matrix.python }}
          path: dist
